filters:
  base_path: Filters/

  filter_names:
    - cfht_u_flux_ujy
    - hsc_g_flux_ujy
    - hsc_r_flux_ujy
    - hsc_i_flux_ujy
    - hsc_z_flux_ujy
    - hsc_y_flux_ujy
    - nisp_y_flux_ujy
    - nisp_j_flux_ujy
    - nisp_h_flux_ujy
    - irac_ch1_flux_ujy
    - irac_ch2_flux_ujy

  list:
    - CFHT_MegaCam.u.dat
    - Subaru_HSC.g.dat
    - Subaru_HSC.r.dat
    - Subaru_HSC.i.dat
    - Subaru_HSC.z.dat
    - Subaru_HSC.y.dat
    - Euclid_NISP.Y.dat
    - Euclid_NISP.J.dat
    - Euclid_NISP.H.dat
    - Spitzer_IRAC.I1.dat
    - Spitzer_IRAC.I2.dat

  filter_centers:
    - 3665.89 
    - 4850.98 
    - 6265.24 
    - 7767.72 
    - 8917.86 
    - 9789.78 
    - 10866.24 
    - 13766.64 
    - 17825.15 
    - 35572.59 
    - 45049.28

    